package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 1:07:34 AM by Hibernate Tools 3.6.0



/**
 * CenterTrainingId generated by hbm2java
 */
public class CenterTrainingId  implements java.io.Serializable {


     private int centerIdFk;
     private int trainingIdFk;

    public CenterTrainingId() {
    }

    public CenterTrainingId(int centerIdFk, int trainingIdFk) {
       this.centerIdFk = centerIdFk;
       this.trainingIdFk = trainingIdFk;
    }
   
    public int getCenterIdFk() {
        return this.centerIdFk;
    }
    
    public void setCenterIdFk(int centerIdFk) {
        this.centerIdFk = centerIdFk;
    }
    public int getTrainingIdFk() {
        return this.trainingIdFk;
    }
    
    public void setTrainingIdFk(int trainingIdFk) {
        this.trainingIdFk = trainingIdFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenterTrainingId) ) return false;
		 CenterTrainingId castOther = ( CenterTrainingId ) other; 
         
		 return (this.getCenterIdFk()==castOther.getCenterIdFk())
 && (this.getTrainingIdFk()==castOther.getTrainingIdFk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCenterIdFk();
         result = 37 * result + this.getTrainingIdFk();
         return result;
   }   


}


