package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 9:46:56 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.json.Json;
import javax.json.JsonObject;
import javax.json.JsonObjectBuilder;

/**
 * Center generated by hbm2java
 */
public class Center  implements java.io.Serializable {


     private Integer centerIdPk;
     private String centerName;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String pin;
     private String description;
     private double latitude;
     private double longitude;
     private Set studentCenters = new HashSet(0);
     private Set centerTrainings = new HashSet(0);

    public Center() {
    }

	
    public Center(String centerName, String addressLine1, String city, double latitude, double longitude) {
        this.centerName = centerName;
        this.addressLine1 = addressLine1;
        this.city = city;
        this.latitude = latitude;
        this.longitude = longitude;
    }
    public Center(String centerName, String addressLine1, String addressLine2, String city, String pin, String description, double latitude, double longitude, Set studentCenters, Set centerTrainings) {
       this.centerName = centerName;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.pin = pin;
       this.description = description;
       this.latitude = latitude;
       this.longitude = longitude;
       this.studentCenters = studentCenters;
       this.centerTrainings = centerTrainings;
    }
   
    public Integer getCenterIdPk() {
        return this.centerIdPk;
    }
    
    public void setCenterIdPk(Integer centerIdPk) {
        this.centerIdPk = centerIdPk;
    }
    public String getCenterName() {
        return this.centerName;
    }
    
    public void setCenterName(String centerName) {
        this.centerName = centerName;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public Set getStudentCenters() {
        return this.studentCenters;
    }
    
    public void setStudentCenters(Set studentCenters) {
        this.studentCenters = studentCenters;
    }
    public Set getCenterTrainings() {
        return this.centerTrainings;
    }
    
    public void setCenterTrainings(Set centerTrainings) {
        this.centerTrainings = centerTrainings;
    }

    @Override
    public String toString(){
        JsonObjectBuilder builder = Json.createObjectBuilder();
        builder.add("id",centerIdPk)
                .add("centerName", centerName)
                .add("addressLine1", addressLine1)
                .add("addressLine2",addressLine2)
                .add("city", city)
                .add("pin", pin)
                .add("description", description)
                .add("latitude", latitude)
                .add("longitude",longitude);
        return builder.build().toString();
    }
    
    public JsonObject getJSONObject(){
        JsonObjectBuilder builder = Json.createObjectBuilder();
        builder.add("id",centerIdPk)
                .add("centerName", centerName)
                .add("addressLine1", addressLine1)
                .add("addressLine2",addressLine2)
                .add("city", city)
                .add("pin", pin)
                .add("description", description)
                .add("latitude", latitude)
                .add("longitude",longitude);
        return builder.build();
    }
}


