package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 1:07:34 AM by Hibernate Tools 3.6.0



/**
 * CenterTraining generated by hbm2java
 */
public class CenterTraining  implements java.io.Serializable {


     private CenterTrainingId id;
     private Training training;
     private Center center;

    public CenterTraining() {
    }

    public CenterTraining(CenterTrainingId id, Training training, Center center) {
       this.id = id;
       this.training = training;
       this.center = center;
    }
   
    public CenterTrainingId getId() {
        return this.id;
    }
    
    public void setId(CenterTrainingId id) {
        this.id = id;
    }
    public Training getTraining() {
        return this.training;
    }
    
    public void setTraining(Training training) {
        this.training = training;
    }
    public Center getCenter() {
        return this.center;
    }
    
    public void setCenter(Center center) {
        this.center = center;
    }

}