package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 9:46:56 PM by Hibernate Tools 3.6.0



/**
 * CenterTraining generated by hbm2java
 */
public class CenterTraining  implements java.io.Serializable {


     private Integer centreTrainingIdPk;
     private Training training;
     private Center center;

    public CenterTraining() {
    }

    public CenterTraining(Training training, Center center) {
       this.training = training;
       this.center = center;
    }
   
    public Integer getCentreTrainingIdPk() {
        return this.centreTrainingIdPk;
    }
    
    public void setCentreTrainingIdPk(Integer centreTrainingIdPk) {
        this.centreTrainingIdPk = centreTrainingIdPk;
    }
    public Training getTraining() {
        return this.training;
    }
    
    public void setTraining(Training training) {
        this.training = training;
    }
    public Center getCenter() {
        return this.center;
    }
    
    public void setCenter(Center center) {
        this.center = center;
    }




}


