package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 9:46:56 PM by Hibernate Tools 3.6.0



/**
 * EmployerStudent generated by hbm2java
 */
public class EmployerStudent  implements java.io.Serializable {


     private Integer empStdIdPk;
     private UserMaster userMasterByStudentIdFk;
     private UserMaster userMasterByEmployerIdFk;

    public EmployerStudent() {
    }

    public EmployerStudent(UserMaster userMasterByStudentIdFk, UserMaster userMasterByEmployerIdFk) {
       this.userMasterByStudentIdFk = userMasterByStudentIdFk;
       this.userMasterByEmployerIdFk = userMasterByEmployerIdFk;
    }
   
    public Integer getEmpStdIdPk() {
        return this.empStdIdPk;
    }
    
    public void setEmpStdIdPk(Integer empStdIdPk) {
        this.empStdIdPk = empStdIdPk;
    }
    public UserMaster getUserMasterByStudentIdFk() {
        return this.userMasterByStudentIdFk;
    }
    
    public void setUserMasterByStudentIdFk(UserMaster userMasterByStudentIdFk) {
        this.userMasterByStudentIdFk = userMasterByStudentIdFk;
    }
    public UserMaster getUserMasterByEmployerIdFk() {
        return this.userMasterByEmployerIdFk;
    }
    
    public void setUserMasterByEmployerIdFk(UserMaster userMasterByEmployerIdFk) {
        this.userMasterByEmployerIdFk = userMasterByEmployerIdFk;
    }




}


