package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 1:07:34 AM by Hibernate Tools 3.6.0



/**
 * EmployerStudentId generated by hbm2java
 */
public class EmployerStudentId  implements java.io.Serializable {


     private int employerIdFk;
     private int studentIdFk;

    public EmployerStudentId() {
    }

    public EmployerStudentId(int employerIdFk, int studentIdFk) {
       this.employerIdFk = employerIdFk;
       this.studentIdFk = studentIdFk;
    }
   
    public int getEmployerIdFk() {
        return this.employerIdFk;
    }
    
    public void setEmployerIdFk(int employerIdFk) {
        this.employerIdFk = employerIdFk;
    }
    public int getStudentIdFk() {
        return this.studentIdFk;
    }
    
    public void setStudentIdFk(int studentIdFk) {
        this.studentIdFk = studentIdFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmployerStudentId) ) return false;
		 EmployerStudentId castOther = ( EmployerStudentId ) other; 
         
		 return (this.getEmployerIdFk()==castOther.getEmployerIdFk())
 && (this.getStudentIdFk()==castOther.getStudentIdFk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmployerIdFk();
         result = 37 * result + this.getStudentIdFk();
         return result;
   }   


}


