package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 1:07:34 AM by Hibernate Tools 3.6.0



/**
 * EmployerStudent generated by hbm2java
 */
public class EmployerStudent  implements java.io.Serializable {


     private EmployerStudentId id;
     private UserMaster userMasterByStudentIdFk;
     private UserMaster userMasterByEmployerIdFk;

    public EmployerStudent() {
    }

    public EmployerStudent(EmployerStudentId id, UserMaster userMasterByStudentIdFk, UserMaster userMasterByEmployerIdFk) {
       this.id = id;
       this.userMasterByStudentIdFk = userMasterByStudentIdFk;
       this.userMasterByEmployerIdFk = userMasterByEmployerIdFk;
    }
   
    public EmployerStudentId getId() {
        return this.id;
    }
    
    public void setId(EmployerStudentId id) {
        this.id = id;
    }
    public UserMaster getUserMasterByStudentIdFk() {
        return this.userMasterByStudentIdFk;
    }
    
    public void setUserMasterByStudentIdFk(UserMaster userMasterByStudentIdFk) {
        this.userMasterByStudentIdFk = userMasterByStudentIdFk;
    }
    public UserMaster getUserMasterByEmployerIdFk() {
        return this.userMasterByEmployerIdFk;
    }
    
    public void setUserMasterByEmployerIdFk(UserMaster userMasterByEmployerIdFk) {
        this.userMasterByEmployerIdFk = userMasterByEmployerIdFk;
    }




}


