package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 9:46:56 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer roleIdPk;
     private String roleName;
     private String description;
     private Set userRoles = new HashSet(0);

    public Role() {
    }

	
    public Role(String roleName) {
        this.roleName = roleName;
    }
    public Role(String roleName, String description, Set userRoles) {
       this.roleName = roleName;
       this.description = description;
       this.userRoles = userRoles;
    }
   
    public Integer getRoleIdPk() {
        return this.roleIdPk;
    }
    
    public void setRoleIdPk(Integer roleIdPk) {
        this.roleIdPk = roleIdPk;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set userRoles) {
        this.userRoles = userRoles;
    }




}


