package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 1:07:34 AM by Hibernate Tools 3.6.0



/**
 * StudentCenter generated by hbm2java
 */
public class StudentCenter  implements java.io.Serializable {


     private StudentCenterId id;
     private UserMaster userMaster;
     private Center center;

    public StudentCenter() {
    }

    public StudentCenter(StudentCenterId id, UserMaster userMaster, Center center) {
       this.id = id;
       this.userMaster = userMaster;
       this.center = center;
    }
   
    public StudentCenterId getId() {
        return this.id;
    }
    
    public void setId(StudentCenterId id) {
        this.id = id;
    }
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    public Center getCenter() {
        return this.center;
    }
    
    public void setCenter(Center center) {
        this.center = center;
    }




}


