package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 9:46:56 PM by Hibernate Tools 3.6.0



/**
 * StudentCenter generated by hbm2java
 */
public class StudentCenter  implements java.io.Serializable {


     private Integer stdCenterIdPk;
     private UserMaster userMaster;
     private Center center;

    public StudentCenter() {
    }

    public StudentCenter(UserMaster userMaster, Center center) {
       this.userMaster = userMaster;
       this.center = center;
    }
   
    public Integer getStdCenterIdPk() {
        return this.stdCenterIdPk;
    }
    
    public void setStdCenterIdPk(Integer stdCenterIdPk) {
        this.stdCenterIdPk = stdCenterIdPk;
    }
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    public Center getCenter() {
        return this.center;
    }
    
    public void setCenter(Center center) {
        this.center = center;
    }
}


