package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 1:07:34 AM by Hibernate Tools 3.6.0



/**
 * StudentCenterId generated by hbm2java
 */
public class StudentCenterId  implements java.io.Serializable {


     private int studentIdFk;
     private int centerIdFk;

    public StudentCenterId() {
    }

    public StudentCenterId(int studentIdFk, int centerIdFk) {
       this.studentIdFk = studentIdFk;
       this.centerIdFk = centerIdFk;
    }
   
    public int getStudentIdFk() {
        return this.studentIdFk;
    }
    
    public void setStudentIdFk(int studentIdFk) {
        this.studentIdFk = studentIdFk;
    }
    public int getCenterIdFk() {
        return this.centerIdFk;
    }
    
    public void setCenterIdFk(int centerIdFk) {
        this.centerIdFk = centerIdFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentCenterId) ) return false;
		 StudentCenterId castOther = ( StudentCenterId ) other; 
         
		 return (this.getStudentIdFk()==castOther.getStudentIdFk())
 && (this.getCenterIdFk()==castOther.getCenterIdFk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentIdFk();
         result = 37 * result + this.getCenterIdFk();
         return result;
   }   


}


