package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 9:46:56 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private Integer subjectIdPk;
     private String subjectName;
     private Set trainingSubjects = new HashSet(0);
     private Set subjectTeachers = new HashSet(0);

    public Subject() {
    }

	
    public Subject(String subjectName) {
        this.subjectName = subjectName;
    }
    public Subject(String subjectName, Set trainingSubjects, Set subjectTeachers) {
       this.subjectName = subjectName;
       this.trainingSubjects = trainingSubjects;
       this.subjectTeachers = subjectTeachers;
    }
   
    public Integer getSubjectIdPk() {
        return this.subjectIdPk;
    }
    
    public void setSubjectIdPk(Integer subjectIdPk) {
        this.subjectIdPk = subjectIdPk;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public Set getTrainingSubjects() {
        return this.trainingSubjects;
    }
    
    public void setTrainingSubjects(Set trainingSubjects) {
        this.trainingSubjects = trainingSubjects;
    }
    public Set getSubjectTeachers() {
        return this.subjectTeachers;
    }
    
    public void setSubjectTeachers(Set subjectTeachers) {
        this.subjectTeachers = subjectTeachers;
    }




}


