package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 1:07:34 AM by Hibernate Tools 3.6.0



/**
 * SubjectTeacher generated by hbm2java
 */
public class SubjectTeacher  implements java.io.Serializable {


     private SubjectTeacherId id;
     private Subject subject;
     private UserMaster userMaster;

    public SubjectTeacher() {
    }

    public SubjectTeacher(SubjectTeacherId id, Subject subject, UserMaster userMaster) {
       this.id = id;
       this.subject = subject;
       this.userMaster = userMaster;
    }
   
    public SubjectTeacherId getId() {
        return this.id;
    }
    
    public void setId(SubjectTeacherId id) {
        this.id = id;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }




}


