package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 1:07:34 AM by Hibernate Tools 3.6.0



/**
 * SubjectTeacherId generated by hbm2java
 */
public class SubjectTeacherId  implements java.io.Serializable {


     private int subjectIdFk;
     private int teacherIdFk;

    public SubjectTeacherId() {
    }

    public SubjectTeacherId(int subjectIdFk, int teacherIdFk) {
       this.subjectIdFk = subjectIdFk;
       this.teacherIdFk = teacherIdFk;
    }
   
    public int getSubjectIdFk() {
        return this.subjectIdFk;
    }
    
    public void setSubjectIdFk(int subjectIdFk) {
        this.subjectIdFk = subjectIdFk;
    }
    public int getTeacherIdFk() {
        return this.teacherIdFk;
    }
    
    public void setTeacherIdFk(int teacherIdFk) {
        this.teacherIdFk = teacherIdFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubjectTeacherId) ) return false;
		 SubjectTeacherId castOther = ( SubjectTeacherId ) other; 
         
		 return (this.getSubjectIdFk()==castOther.getSubjectIdFk())
 && (this.getTeacherIdFk()==castOther.getTeacherIdFk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSubjectIdFk();
         result = 37 * result + this.getTeacherIdFk();
         return result;
   }   


}


