package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 1:07:34 AM by Hibernate Tools 3.6.0



/**
 * TrainingSubjectId generated by hbm2java
 */
public class TrainingSubjectId  implements java.io.Serializable {


     private int trainingIdFk;
     private int subjectIdFk;

    public TrainingSubjectId() {
    }

    public TrainingSubjectId(int trainingIdFk, int subjectIdFk) {
       this.trainingIdFk = trainingIdFk;
       this.subjectIdFk = subjectIdFk;
    }
   
    public int getTrainingIdFk() {
        return this.trainingIdFk;
    }
    
    public void setTrainingIdFk(int trainingIdFk) {
        this.trainingIdFk = trainingIdFk;
    }
    public int getSubjectIdFk() {
        return this.subjectIdFk;
    }
    
    public void setSubjectIdFk(int subjectIdFk) {
        this.subjectIdFk = subjectIdFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrainingSubjectId) ) return false;
		 TrainingSubjectId castOther = ( TrainingSubjectId ) other; 
         
		 return (this.getTrainingIdFk()==castOther.getTrainingIdFk())
 && (this.getSubjectIdFk()==castOther.getSubjectIdFk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTrainingIdFk();
         result = 37 * result + this.getSubjectIdFk();
         return result;
   }   


}


