package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 9:46:56 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TrainingType generated by hbm2java
 */
public class TrainingType  implements java.io.Serializable {


     private Integer trainingTypeIdPk;
     private String trainingTypeName;
     private String description;
     private Set trainings = new HashSet(0);

    public TrainingType() {
    }

	
    public TrainingType(String trainingTypeName) {
        this.trainingTypeName = trainingTypeName;
    }
    public TrainingType(String trainingTypeName, String description, Set trainings) {
       this.trainingTypeName = trainingTypeName;
       this.description = description;
       this.trainings = trainings;
    }
   
    public Integer getTrainingTypeIdPk() {
        return this.trainingTypeIdPk;
    }
    
    public void setTrainingTypeIdPk(Integer trainingTypeIdPk) {
        this.trainingTypeIdPk = trainingTypeIdPk;
    }
    public String getTrainingTypeName() {
        return this.trainingTypeName;
    }
    
    public void setTrainingTypeName(String trainingTypeName) {
        this.trainingTypeName = trainingTypeName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTrainings() {
        return this.trainings;
    }
    
    public void setTrainings(Set trainings) {
        this.trainings = trainings;
    }




}


