package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 9:46:56 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.json.Json;
import javax.json.JsonObject;
import javax.json.JsonObjectBuilder;

/**
 * Training generated by hbm2java
 */
public class Training  implements java.io.Serializable {


     private Integer trainingIdPk;
     private TrainingType trainingType;
     private String trainingName;
     private String description;
     private Set trainingSubjects = new HashSet(0);
     private Set centerTrainings = new HashSet(0);

    public Training() {
    }

	
    public Training(TrainingType trainingType, String trainingName) {
        this.trainingType = trainingType;
        this.trainingName = trainingName;
    }
    public Training(TrainingType trainingType, String trainingName, String description, Set trainingSubjects, Set centerTrainings) {
       this.trainingType = trainingType;
       this.trainingName = trainingName;
       this.description = description;
       this.trainingSubjects = trainingSubjects;
       this.centerTrainings = centerTrainings;
    }
   
    public Integer getTrainingIdPk() {
        return this.trainingIdPk;
    }
    
    public void setTrainingIdPk(Integer trainingIdPk) {
        this.trainingIdPk = trainingIdPk;
    }
    public TrainingType getTrainingType() {
        return this.trainingType;
    }
    
    public void setTrainingType(TrainingType trainingType) {
        this.trainingType = trainingType;
    }
    public String getTrainingName() {
        return this.trainingName;
    }
    
    public void setTrainingName(String trainingName) {
        this.trainingName = trainingName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTrainingSubjects() {
        return this.trainingSubjects;
    }
    
    public void setTrainingSubjects(Set trainingSubjects) {
        this.trainingSubjects = trainingSubjects;
    }
    public Set getCenterTrainings() {
        return this.centerTrainings;
    }
    
    public void setCenterTrainings(Set centerTrainings) {
        this.centerTrainings = centerTrainings;
    }
    @Override
    public String toString(){
        JsonObjectBuilder builder = Json.createObjectBuilder();
        builder.add("id",trainingIdPk)
                .add("name", trainingName)
                .add("description", description)
                .add("typeId",trainingType.getTrainingTypeIdPk())
                .add("type",trainingType.getTrainingTypeName());
        return builder.build().toString();
    }
    
    public JsonObject getJSONObject(){
        JsonObjectBuilder builder = Json.createObjectBuilder();
        builder.add("id",trainingIdPk)
                .add("name", trainingName)
                .add("description", description)
                .add("typeId",trainingType.getTrainingTypeIdPk())
                .add("type",trainingType.getTrainingTypeName());
        return builder.build();
    }
}


