package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 9:46:56 PM by Hibernate Tools 3.6.0



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer userRoleIdPk;
     private UserMaster userMaster;
     private Role role;

    public UserRole() {
    }

    public UserRole(UserMaster userMaster, Role role) {
       this.userMaster = userMaster;
       this.role = role;
    }
   
    public Integer getUserRoleIdPk() {
        return this.userRoleIdPk;
    }
    
    public void setUserRoleIdPk(Integer userRoleIdPk) {
        this.userRoleIdPk = userRoleIdPk;
    }
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }




}


