package com.cnqaos.hibernate.pojo;
// Generated 23 Aug, 2014 1:07:34 AM by Hibernate Tools 3.6.0



/**
 * UserRoleId generated by hbm2java
 */
public class UserRoleId  implements java.io.Serializable {


     private int userIdFk;
     private int roleIdFk;

    public UserRoleId() {
    }

    public UserRoleId(int userIdFk, int roleIdFk) {
       this.userIdFk = userIdFk;
       this.roleIdFk = roleIdFk;
    }
   
    public int getUserIdFk() {
        return this.userIdFk;
    }
    
    public void setUserIdFk(int userIdFk) {
        this.userIdFk = userIdFk;
    }
    public int getRoleIdFk() {
        return this.roleIdFk;
    }
    
    public void setRoleIdFk(int roleIdFk) {
        this.roleIdFk = roleIdFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserRoleId) ) return false;
		 UserRoleId castOther = ( UserRoleId ) other; 
         
		 return (this.getUserIdFk()==castOther.getUserIdFk())
 && (this.getRoleIdFk()==castOther.getRoleIdFk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserIdFk();
         result = 37 * result + this.getRoleIdFk();
         return result;
   }   


}


